name             'ddclient'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ddclient'
long_description 'Installs/Configures ddclient'
version          '0.1.0'
